name: PurpleReports
version: '${project.version}'
main: dev.mruniverse.purplereports.spigot.PurpleReports
api-version: 1.13
authors: [ JustJustin ]
description: Simple Report Plugin
website: github.com/MrUniverse44/PurpleReports
